In [1]:
import pandas as pd
import numpy as np
df_policy_raw = pd.read_csv('../Tbrain_Insurance/policy_claim/policy_0702.csv')
df_claim_raw = pd.read_csv('../Tbrain_Insurance/policy_claim/claim_0702.csv')
df_training_raw = pd.read_csv('../Tbrain_Insurance/training-set.csv')
df_testing_raw = pd.read_csv('../Tbrain_Insurance/testing-set.csv')

In [14]:
df_policy_claim = df_policy_raw.merge(df_claim_raw, left_on = ['Policy_Number', 'Insurance_Coverage'], right_on = ['Policy_Number', 'Coverage'], how= 'left')
df_policy_claim = df_policy_claim.merge(df_training_raw, on = ['Policy_Number'], how= 'left')
df_policy_claim = df_policy_claim.merge(df_testing_raw, on = ['Policy_Number'], how= 'left')

In [15]:
df_policy_claim['Next_Premium_x'] = df_policy_claim['Next_Premium_x'].fillna(0)
df_policy_claim['Next_Premium_y'] = df_policy_claim['Next_Premium_y'].fillna(0)
df_policy_claim['Next_Premium'] = df_policy_claim['Next_Premium_x'] + df_policy_claim['Next_Premium_y']
df_policy_claim['Next_Premium'].head()

0    2412.0
1    2412.0
2    3129.0
3    3129.0
4       0.0
Name: Next_Premium, dtype: float64

In [18]:
df_policy_claim_grouped = df_policy_claim.groupby(['Policy_Number']).first().reset_index()

In [20]:
df_policy_claim_grouped[df_policy_claim_grouped['Next_Premium'] == 0].shape[0]/df_policy_claim_grouped.shape[0]

0.13155010490416286

In [21]:
df_temp = df_policy_claim_grouped[df_policy_claim_grouped['Next_Premium'] == 0]

In [22]:
df_temp.describe()

,Manafactured_Year_and_Month,Engine_Displacement_(Cubic_Centimeter),Imported_or_Domestic_Car,qpt,Insured_Amount1,Insured_Amount2,Insured_Amount3,Coverage_Deductible_if_applied,Premium,Replacement_cost_of_insured_vehicle,...,Paid_Loss_Amount,paid_Expenses_Amount,Salvage_or_Subrogation?,At_Fault?,"Claim_Status_(close,_open,_reopen_etc)",Deductible,number_of_claimants,Next_Premium_x,Next_Premium_y,Next_Premium
count,46210.000000,46210.000000,46210.000000,46210.000000,4.621000e+04,4.621000e+04,4.621000e+04,46210.000000,46210.000000,46210.000000,...,4.974000e+03,4974.000000,4974.000000,4971.000000,4974.0,4974.000000,4974.000000,46210.0,46210.0,46210.0
mean,2004.860593,1970.884484,15.301969,4.955053,9.053115e+05,3.096321e+05,7.124412e+06,21.738282,2451.065375,90.971264,...,3.338986e+04,279.012465,6.063932,65.185878,1.0,122.156815,1.869672,0.0,0.0,0.0
std,5.844431,580.817893,10.772082,1.108630,1.315474e+06,1.477161e+06,1.291324e+07,1343.372739,5865.733830,87.555189,...,1.425737e+05,497.974011,302.843522,42.401227,0.0,1762.400400,0.172820,0.0,0.0,0.0
min,1921.000000,60.000000,10.000000,2.000000,0.000000e+00,0.000000e+00,0.000000e+00,-100000.000000,0.000000,2.000000,...,0.000000e+00,0.000000,0.000000,0.000000,1.0,0.000000,1.551000,0.0,0.0,0.0
25%,2001.000000,1598.000000,10.000000,5.000000,0.000000e+00,0.000000e+00,1.010000e+05,0.000000,450.000000,53.900000,...,0.000000e+00,0.000000,0.000000,30.000000,1.0,0.000000,1.787000,0.0,0.0,0.0
50%,2005.000000,1895.000000,10.000000,5.000000,1.000000e+04,0.000000e+00,2.000000e+06,0.000000,1205.500000,67.900000,...,7.652000e+03,0.000000,0.000000,100.000000,1.0,0.000000,1.787000,0.0,0.0,0.0
75%,2010.000000,2198.000000,10.000000,5.000000,2.000000e+06,0.000000e+00,1.000000e+07,0.000000,2016.000000,89.200000,...,2.375550e+04,700.000000,0.000000,100.000000,1.0,0.000000,1.981000,0.0,0.0,0.0
max,2016.000000,6750.000000,90.000000,20.000000,2.000000e+07,2.000000e+07,1.400000e+08,100000.000000,257916.000000,6108.000000,...,4.000000e+06,5050.000000,15919.000000,100.000000,1.0,51418.000000,3.475000,0.0,0.0,0.0